name: etl-env
channels:
  - defaults
  - conda-forge
dependencies:
  # Python dependencies
  - python>=3.6,<3.7
  - shapely
  - psycopg2
  - pyproj
  - gpxpy
  - requests
  - tqdm
  - jupyter
  - pandas
  - pip
  - pip :
    - azure
    - azure-storage-blob
    - gopro2gpx==0.1
    - moviepy

